[workspace]
members = [
    # "standalone", # to be removed after rearrangement
    "machine",
    "supervisor",
    "hal/d1-hal",
    "d1-rom-rt",
    "d1-rom-rt/macros",
    "hal/aw-soc",
    "hal/base-address",
    "xtask",
]
default-members = ["xtask"]
