[workspace]
members = [
    # "standalone", # to be removed after rearrangement
    "bootstrap",
    "machine",
    "supervisor",
    "d1-rom-rt",
    "d1-rom-rt/macros",
    "hal/aw-soc",
    "hal/flashes",
    "xtask",
]
default-members = ["xtask"]
