[package]
name = "rustsbi-machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rom-rt = { path = "../rom-rt", features = ["log"]}
ufmt = { version = "0.2.0", optional = true }

[features]
allwinner-d1 = ["rom-rt/allwinner-d1", "dep:ufmt"]
