[package]
name = "rustsbi-machine"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = "0.11.0"

[features]
default = []

[[bin]]
name = "rustsbi-machine"
test = false
bench = false
